### ISSUE TITLE
Browser versions don't align

### ISSUE THREAD

**Issue by mihawk90** [cfjedimaster/brackets-caniuse#16]
So this has been an issue for a while now but never really bothered to report since it's still usable.

The browser versions don't match up at all with the "Previous", "Current" and "Future" lines.

![image](https://cloud.githubusercontent.com/assets/556162/8144317/d90bd214-11d7-11e5-81bc-460f4b4e5239.png)

Clearly IE11, Safari 8, Safari iOS and Android (Chrome) 40 are the latest versions, but as you can see they don't match up at all.

It's not really important, but as the rest of the extensions seems to work just fine this could be adressed :D

**Comment by cfjedimaster** [comment]
I'm not understanding what you are saying here. What doesn't match up?

On Sat, Jun 13, 2015 at 7:26 AM, Tarulia <notifications@github.com> wrote:

> So this has been an issue for a while now but never really bothered to
> report since it's still usable.
>
> The browser versions don't match up at all with the "Previous", "Current"
> and "Future" lines.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/556162/8144317/d90bd214-11d7-11e5-81bc-460f4b4e5239.png>
>
> Clearly IE11, Safari 8, Safari iOS and Android (Chrome) 40 are the latest
> versions, but as you can see they don't match up at all.
>
> It's not really important, but as the rest of the extensions seems to work
> just fine this could be adressed :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-caniuse/issues/16>.
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by mihawk90** [comment]
Sorry I was a little busy for a while :)

As you can see on the screenshot, IE11, Safari 8, iOS 8.x and Android 40 are all listed as "previous" version, but as we know, they are all the current version (as can be seen on the caniuse website as well).

The table is basically missing an empty tablecell (spacer) or the "real" previous version (IE10, Safari 7, Android Browser 4.x). They all need to be moved one row down to match up with the "previous", "latest" and "future" rows
